#ifndef TESDATA_FORMNAMES_H
#define TESDATA_FORMNAMES_H

#include "TESFile/Type.h"

#include <QStringView>

#include <algorithm>
#include <array>
#include <utility>

namespace TESData
{

constexpr auto FormNames = std::to_array<std::pair<TESFile::Type, QStringView>>({
    {"AACT"_ts, u"Actor Action"},
    {"ACHR"_ts, u"Placed NPC"},
    {"ACTI"_ts, u"Activator"},
    {"ADDN"_ts, u"AddOnNode"},
    {"ALCH"_ts, u"Potion"},
    {"AMMO"_ts, u"Ammo"},
    {"ANIO"_ts, u"AnimObject"},
    {"APPA"_ts, u"Alchemical Apparatus"},
    {"ARMA"_ts, u"ArmorAddon"},
    {"ARMO"_ts, u"Armor"},
    {"ARTO"_ts, u"Art Object"},
    {"ASPC"_ts, u"Acoustic Space"},
    {"ASTP"_ts, u"Association Type"},
    {"AVIF"_ts, u"ActorValueInfo"},
    {"BOOK"_ts, u"Book"},
    {"BPTD"_ts, u"BodyPartData"},
    {"CAMS"_ts, u"CameraShot"},
    {"CELL"_ts, u"Cell"},
    {"CLAS"_ts, u"Class"},
    {"CLDC"_ts, u""},
    {"CLFM"_ts, u"ColorForm"},
    {"CLMT"_ts, u"Climate"},
    {"COBJ"_ts, u"Constructible Object"},
    {"COLL"_ts, u"Collision Layer"},
    {"CONT"_ts, u"Container"},
    {"CPTH"_ts, u"Camera Path"},
    {"CSTY"_ts, u"CombatStyle"},
    {"DEBR"_ts, u"Debris"},
    {"DIAL"_ts, u"Dialogue Topic"},
    {"DLBR"_ts, u"Dialogue Branch"},
    {"DLVW"_ts, u"Dialogue View"},
    {"DOBJ"_ts, u"Default Object"},
    {"DOOR"_ts, u"Door"},
    {"DUAL"_ts, u"Dual Cast Data"},
    {"ECZN"_ts, u"Encounter Zone"},
    {"EFSH"_ts, u"EffectShader"},
    {"ENCH"_ts, u"Enchantment"},
    {"EQUP"_ts, u"Equip Slot"},
    {"EXPL"_ts, u"Explosion"},
    {"EYES"_ts, u"Eyes"},
    {"FACT"_ts, u"Faction"},
    {"FLOR"_ts, u"Flora"},
    {"FLST"_ts, u"FormList"},
    {"FSTP"_ts, u"Footstep"},
    {"FSTS"_ts, u"Footstep Set"},
    {"FURN"_ts, u"Furniture"},
    {"GLOB"_ts, u"Global"},
    {"GMST"_ts, u"GameSetting"},
    {"GRAS"_ts, u"Grass"},
    {"HAIR"_ts, u""},
    {"HAZD"_ts, u"Hazard"},
    {"HDPT"_ts, u"HeadPart"},
    {"IDLE"_ts, u"Animation"},
    {"IDLM"_ts, u"IdleMarker"},
    {"IMAD"_ts, u"Imagespace Modifier"},
    {"IMGS"_ts, u"Imagespace"},
    {"INFO"_ts, u"Topic Info"},
    {"INGR"_ts, u"Ingredient"},
    {"IPCT"_ts, u"ImpactData"},
    {"IPDS"_ts, u"ImpactDataSet"},
    {"KEYM"_ts, u"Key"},
    {"KYWD"_ts, u"Keyword"},
    {"LAND"_ts, u"Landscape"},
    {"LCRT"_ts, u"Location Ref Type"},
    {"LCTN"_ts, u"Location"},
    {"LENS"_ts, u"LensFlare"},
    {"LGTM"_ts, u"Lighting Template"},
    {"LIGH"_ts, u"Light"},
    {"LSCR"_ts, u"LoadScreen"},
    {"LTEX"_ts, u"LandTexture"},
    {"LVLI"_ts, u"LeveledItem"},
    {"LVLN"_ts, u"LeveledCharacter"},
    {"LVSP"_ts, u"LeveledSpell"},
    {"MATO"_ts, u"Material Object"},
    {"MATT"_ts, u"Material Type"},
    {"MESG"_ts, u"Message"},
    {"MGEF"_ts, u"Magic Effect"},
    {"MISC"_ts, u"MiscItem"},
    {"MOVT"_ts, u"Movement Type"},
    {"MSTT"_ts, u"MovableStatic"},
    {"MUSC"_ts, u"Music Type"},
    {"MUST"_ts, u"Music Track"},
    {"NAVI"_ts, u"Navigation Mesh Info Map"},
    {"NAVM"_ts, u"Navigation Mesh"},
    {"NPC_"_ts, u"Actor"},
    {"OTFT"_ts, u"Outfit"},
    {"PACK"_ts, u"Package"},
    {"PARW"_ts, u"Placed Arrow"},
    {"PBAR"_ts, u"Placed Barrier"},
    {"PBEA"_ts, u"Placed Beam"},
    {"PCON"_ts, u"Placed Cone/Voice"},
    {"PERK"_ts, u"Perk"},
    {"PFLA"_ts, u"Placed Flame"},
    {"PGRE"_ts, u"Placed Projectile"},
    {"PHZD"_ts, u"Placed Hazard"},
    {"PLYR"_ts, u"Player Reference"},
    {"PMIS"_ts, u"Placed Missile"},
    {"PROJ"_ts, u"Projectile"},
    {"PWAT"_ts, u""},
    {"QUST"_ts, u"Quest"},
    {"RACE"_ts, u"Race"},
    {"REFR"_ts, u"Placed Object"},
    {"REGN"_ts, u"Region"},
    {"RELA"_ts, u"Relationship"},
    {"REVB"_ts, u"Reverb Parameters"},
    {"RFCT"_ts, u"Visual Effect"},
    {"RGDL"_ts, u""},
    {"SCEN"_ts, u"Scene"},
    {"SCOL"_ts, u"Static Collection"},
    {"SCPT"_ts, u""},
    {"SCRL"_ts, u"Scroll"},
    {"SHOU"_ts, u"Shout"},
    {"SLGM"_ts, u"Soul Gem"},
    {"SMBN"_ts, u"Story Manager Branch Node"},
    {"SMEN"_ts, u"Story Manager Event Node"},
    {"SMQN"_ts, u"Story Manager Quest Node"},
    {"SNCT"_ts, u"Sound Category"},
    {"SNDR"_ts, u"Sound Descriptor"},
    {"SOPM"_ts, u"Sound Output Model"},
    {"SOUN"_ts, u"Sound Marker"},
    {"SPEL"_ts, u"Spell"},
    {"SPGD"_ts, u"Shader Particle Geometry"},
    {"STAT"_ts, u"Static"},
    {"TACT"_ts, u"TalkingActivator"},
    {"TES4"_ts, u"File Header"},
    {"TREE"_ts, u"Tree"},
    {"TXST"_ts, u"TextureSet"},
    {"VOLI"_ts, u"VolumetricLighting"},
    {"VTYP"_ts, u"VoiceType"},
    {"WATR"_ts, u"WaterType"},
    {"WEAP"_ts, u"Weapon"},
    {"WOOP"_ts, u"Word of Power"},
    {"WRLD"_ts, u"World Space"},
    {"WTHR"_ts, u"Weather"},
});

constexpr auto DefaultObjectNames =
    std::to_array<std::pair<TESFile::Type, QStringView>>({
        {"AAAC"_ts, u"Action Activate"},
        {"AAB1"_ts, u"Action Bleedout Start"},
        {"AAB2"_ts, u"Action Bleedout Stop"},
        {"AABA"_ts, u"Action Block Anticipate"},
        {"AABH"_ts, u"Action Block Hit"},
        {"AABI"_ts, u"Action Bumped Into"},
        {"AADA"_ts, u"Action DualAttack"},
        {"AADE"_ts, u"Action Death"},
        {"AADL"_ts, u"Action DualRelease"},
        {"AADR"_ts, u"Action Draw"},
        {"AADW"_ts, u"Action Death Wait"},
        {"AAF1"_ts, u"Action Fly Start"},
        {"AAF2"_ts, u"Action Fly Stop"},
        {"AAFA"_ts, u"Action Fall"},
        {"AAFQ"_ts, u"Action Force Equip"},
        {"AAGU"_ts, u"Action Get Up"},
        {"AAH1"_ts, u"Action Hover Start"},
        {"AAH2"_ts, u"Action Hover Stop"},
        {"AAID"_ts, u"Action Idle"},
        {"AAIS"_ts, u"Action Idle Stop"},
        {"AAJP"_ts, u"Action Jump"},
        {"AALA"_ts, u"Action LeftAttack"},
        {"AALD"_ts, u"Action LeftReady"},
        {"AALI"_ts, u"Action LeftInterrupt"},
        {"AALK"_ts, u"Action Look"},
        {"AALM"_ts, u"Action Large Movement Delta"},
        {"AALN"_ts, u"Action Land"},
        {"AALR"_ts, u"Action LeftRelease"},
        {"AAPA"_ts, u"Action Right Power Attack"},
        {"AAPE"_ts, u"Action Path End"},
        {"AAPS"_ts, u"Action Path Start"},
        {"AAR2"_ts, u"Action Large Recoil"},
        {"AARA"_ts, u"Action RightAttack"},
        {"AARC"_ts, u"Action Recoil"},
        {"AARD"_ts, u"Action RightReady"},
        {"AARI"_ts, u"Action RightInterrupt"},
        {"AARR"_ts, u"Action RightRelease"},
        {"AAS1"_ts, u"Action Stagger Start"},
        {"AASC"_ts, u"Action Shield Change"},
        {"AASH"_ts, u"Action Sheath"},
        {"AASN"_ts, u"Action Sneak"},
        {"AASP"_ts, u"Action Sprint Stop"},
        {"AASS"_ts, u"Action Summoned Start"},
        {"AAST"_ts, u"Action Sprint Start"},
        {"AASW"_ts, u"Action Swim State Change"},
        {"AAVC"_ts, u"Action Voice"},
        {"AAVD"_ts, u"Action VoiceReady"},
        {"AAVI"_ts, u"Action VoiceInterrupt"},
        {"AAVR"_ts, u"Action VoiceRelease"},
        {"AAWH"_ts, u"Action Ward Hit"},
        {"ABSE"_ts, u"Art Object - Absorb Effect"},
        {"ADPA"_ts, u"Action Dual Power Attack"},
        {"AFNP"_ts, u"Keyword - Activator Furniture No Player"},
        {"AHBM"_ts, u"Keyword - Armor Material Heavy Bonemold"},
        {"AHCH"_ts, u"Keyword - Armor Material Heavy Chitin"},
        {"AHNC"_ts, u"Keyword - Armor Material Heavy Nordic"},
        {"AHSM"_ts, u"Keyword - Armor Material Heavy Stalhrim"},
        {"AIDW"_ts, u"Action Idle Warn"},
        {"AIVC"_ts, u"Verlet Cape"},
        {"AKDN"_ts, u"Action Knockdown"},
        {"ALBM"_ts, u"Keyword - Armor Material Light Bonemold"},
        {"ALCH"_ts, u"Keyword - Armor Material Light Chitin"},
        {"ALDM"_ts, u"Ash LOD Material"},
        {"ALHD"_ts, u"Ash LOD Material (HD)"},
        {"ALNC"_ts, u"Keyword - Armor Material Light Nordic"},
        {"ALPA"_ts, u"Action Left Power Attack"},
        {"ALSM"_ts, u"Keyword - Armor Material Light Stalhrim"},
        {"ALTI"_ts, u"Action Listen Idle"},
        {"AMBK"_ts, u"Action Move Backward"},
        {"AMFD"_ts, u"Action Move Forward"},
        {"AMLT"_ts, u"Action Move Left"},
        {"AMRT"_ts, u"Action Move Right"},
        {"AMSP"_ts, u"Action Move Stop"},
        {"AMST"_ts, u"Action Move Start"},
        {"ANML"_ts, u"Keyword - Animal"},
        {"AODA"_ts, u"Keyword - Armor Material Daedric"},
        {"AODB"_ts, u"Keyword - Armor Material Dragonbone"},
        {"AODP"_ts, u"Keyword - Armor Material Dragonplate"},
        {"AODS"_ts, u"Keyword - Armor Material Dragonscale"},
        {"AODW"_ts, u"Keyword - Armor Material Dwarven"},
        {"AOEB"_ts, u"Keyword - Armor Material Ebony"},
        {"AOEL"_ts, u"Keyword - Armor Material Elven"},
        {"AOES"_ts, u"Keyword - Armor Material ElvenSplinted"},
        {"AOFE"_ts, u"Keyword - Armor Material Iron"},
        {"AOFL"_ts, u"Keyword - Armor Material FullLeather"},
        {"AOGL"_ts, u"Keyword - Armor Material Glass"},
        {"AOHI"_ts, u"Keyword - Armor Material Hide"},
        {"AOIB"_ts, u"Keyword - Armor Material IronBanded"},
        {"AOIH"_ts, u"Keyword - Armor Material ImperialHeavy"},
        {"AOIM"_ts, u"Keyword - Armor Material Imperial"},
        {"AOIR"_ts, u"Keyword - Armor Material ImperialReinforced"},
        {"AOOR"_ts, u"Keyword - Armor Material Orcish"},
        {"AOSC"_ts, u"Keyword - Armor Material Scaled"},
        {"AOSD"_ts, u"Keyword - Armor Material Studded"},
        {"AOSK"_ts, u"Keyword - Armor Material Stormcloak"},
        {"AOSP"_ts, u"Keyword - Armor Material SteelPlate"},
        {"AOST"_ts, u"Keyword - Armor Material Steel"},
        {"APSH"_ts, u"Allow Player Shout"},
        {"ARAG"_ts, u"Action Reset Animation Graph"},
        {"AREL"_ts, u"Action Reload"},
        {"ARGI"_ts, u"Action Ragdoll Instant"},
        {"ARTL"_ts, u"Armor Material List"},
        {"ASID"_ts, u"Action Idle Stop Instant"},
        {"ATKI"_ts, u"Action Talking Idle"},
        {"ATLE"_ts, u"Action Turn Left"},
        {"ATRI"_ts, u"Action Turn Right"},
        {"ATSP"_ts, u"Action Turn Stop"},
        {"AVVP"_ts, u"Vampire Available Perks"},
        {"AVWP"_ts, u"Werewolf Available Perks"},
        {"AWWS"_ts, u"Action Waterwalk Start"},
        {"AWWW"_ts, u"Bunny Faction"},
        {"BAPO"_ts, u"Base Potion"},
        {"BAPS"_ts, u"Base Poison"},
        {"BEEP"_ts, u"Keyword - Robot"},
        {"BENA"_ts, u"Base Armor Enchantment"},
        {"BENW"_ts, u"Base Weapon Enchantment"},
        {"BTMS"_ts, u"Battle Music"},
        {"CACA"_ts, u"Commanded Actor Ability"},
        {"CMPX"_ts, u"Complex Scene Object"},
        {"COEX"_ts, u"Keyword - Conditional Explosion"},
        {"COOK"_ts, u"Keyword: Cooking Pot"},
        {"CSTY"_ts, u"Combat Style"},
        {"CWNE"_ts, u"Keyword - Civil War Neutral"},
        {"CWOK"_ts, u"Keyword - Civil War Owner"},
        {"DAED"_ts, u"Keyword - Daedra"},
        {"DBHF"_ts, u"Dark Brotherhood Faction"},
        {"DCMS"_ts, u"Dungeon Cleared Music"},
        {"DCZM"_ts, u"Dragon Crash Zone Marker"},
        {"DDSC"_ts, u"Dialogue Voice Category"},
        {"DEIS"_ts, u"Drug Wears Off Image Space"},
        {"DFMS"_ts, u"Default Music"},
        {"DFTS"_ts, u"Footstep Set"},
        {"DGFL"_ts, u"DialogueFollower Quest"},
        {"DIEN"_ts, u"Keyword - Disallow Enchanting"},
        {"DLMT"_ts, u"Landscape Material"},
        {"DLZM"_ts, u"Dragon Land Zone Marker"},
        {"DMFL"_ts, u"Default MovementType: Fly"},
        {"DMRN"_ts, u"Default MovementType: Run"},
        {"DMSN"_ts, u"Default MovementType: Sneak"},
        {"DMSP"_ts, u"Default MovementType: Sprint"},
        {"DMSW"_ts, u"Default MovementType: Swim"},
        {"DMWL"_ts, u"Default MovementType: Walk"},
        {"DMXL"_ts, u"Dragon Mount No Land List"},
        {"DOP2"_ts, u"Dialogue Output Model (3D)"},
        {"DOP3"_ts, u"Dialogue Output Model (2D)"},
        {"DRAK"_ts, u"Keyword - Dragon"},
        {"DTMS"_ts, u"Death Music"},
        {"EACA"_ts, u"Every Actor Ability"},
        {"EHEQ"_ts, u"EitherHand Equip"},
        {"EPDF"_ts, u"Eat Package Default Food"},
        {"FFFP"_ts, u"Keyword - Furniture Forces 1st Person"},
        {"FFTP"_ts, u"Keyword - Furniture Forces 3rd Person"},
        {"FGPD"_ts, u"Favor Gifts Per Day"},
        {"FMFF"_ts, u"Flying Mount - Fly Fast Worldspaces"},
        {"FMNS"_ts, u"Flying Mount - Disallowed Spells"},
        {"FMYS"_ts, u"Flying Mount - Allowed Spells"},
        {"FORG"_ts, u"Keyword: Forge"},
        {"FPCL"_ts, u"Favor Cost Large"},
        {"FPCM"_ts, u"Favor Cost Medium"},
        {"FPCS"_ts, u"Favor Cost Small"},
        {"FTEL"_ts, u"Male Face Texture Set: Eyes"},
        {"FTGF"_ts, u"Fighters' Guild Faction"},
        {"FTHD"_ts, u"Male Face Texture Set: Head"},
        {"FTHF"_ts, u"Female Face Texture Set: Head"},
        {"FTMF"_ts, u"Female Face Texture Set: Mouth"},
        {"FTML"_ts, u"Favor travel marker location"},
        {"FTMO"_ts, u"Male Face Texture Set: Mouth"},
        {"FTNP"_ts, u"Furniture Test NPC"},
        {"FTRF"_ts, u"Female Face Texture Set: Eyes"},
        {"GCK1"_ts, u"Keyword - Generic Craftable Keyword 01"},
        {"GCK2"_ts, u"Keyword - Generic Craftable Keyword 02"},
        {"GCK3"_ts, u"Keyword - Generic Craftable Keyword 03"},
        {"GCK4"_ts, u"Keyword - Generic Craftable Keyword 04"},
        {"GCK5"_ts, u"Keyword - Generic Craftable Keyword 05"},
        {"GCK6"_ts, u"Keyword - Generic Craftable Keyword 06"},
        {"GCK7"_ts, u"Keyword - Generic Craftable Keyword 07"},
        {"GCK8"_ts, u"Keyword - Generic Craftable Keyword 08"},
        {"GCK9"_ts, u"Keyword - Generic Craftable Keyword 09"},
        {"GCKX"_ts, u"Keyword - Generic Craftable Keyword 10"},
        {"GFAC"_ts, u"Guard Faction"},
        {"GOLD"_ts, u"Gold"},
        {"HBAL"_ts, u"Help - Basic Alchemy"},
        {"HBAT"_ts, u"Help - Attack Target"},
        {"HBBR"_ts, u"Help - Barter"},
        {"HBCO"_ts, u"Help - Basic Cooking"},
        {"HBEC"_ts, u"Help - Basic Enchanting"},
        {"HBFG"_ts, u"Help - Basic Forging"},
        {"HBFM"_ts, u"Help - Flying Mount"},
        {"HBFS"_ts, u"Help - Favorites"},
        {"HBFT"_ts, u"Help - Teamate Favor"},
        {"HBHJ"_ts, u"Help - Jail"},
        {"HBJL"_ts, u"Help - Journal"},
        {"HBLH"_ts, u"Help - Low Health"},
        {"HBLK"_ts, u"Help - Basic Lockpicking (PC)"},
        {"HBLM"_ts, u"Help - Low Magicka"},
        {"HBLS"_ts, u"Help - Low Stamina"},
        {"HBLU"_ts, u"Help - Leveling up"},
        {"HBLX"_ts, u"Help - Basic Lockpicking (Console)"},
        {"HBML"_ts, u"Help - Basic Smelting"},
        {"HBMM"_ts, u"Help - Map Menu"},
        {"HBOC"_ts, u"Help - Basic Object Creation"},
        {"HBSA"_ts, u"Help - Basic Smithing Armor"},
        {"HBSK"_ts, u"Help - Skills Menu"},
        {"HBSM"_ts, u"Help - Basic Smithing Weapon"},
        {"HBTA"_ts, u"Help - Basic Tanning"},
        {"HBTL"_ts, u"Help - Target Lock"},
        {"HBWC"_ts, u"Help - Weapon Charge"},
        {"HCLL"_ts, u"FormList - Hair Color List"},
        {"HFSD"_ts, u"Heartbeat Sound Fast"},
        {"HMPC"_ts, u"Help Manual PC"},
        {"HMXB"_ts, u"Help Manual XBox"},
        {"HRSK"_ts, u"Keyword - Horse"},
        {"HSSD"_ts, u"Heartbeat Sound Slow"},
        {"HVFS"_ts, u"Harvest Failed Sound"},
        {"HVSS"_ts, u"Harvest Sound"},
        {"IMID"_ts, u"ImageSpaceModifier for inventory menu."},
        {"IMLH"_ts, u"Imagespace: Low Health"},
        {"INVP"_ts, u"Inventory Player"},
        {"IOPM"_ts, u"Interface Output Model"},
        {"JRLF"_ts, u"Jarl Faction"},
        {"JWLR"_ts, u"Keyword - Jewelry"},
        {"KHFL"_ts, u"Kinect Help FormList"},
        {"KWBR"_ts, u"Keyword - BeastRace"},
        {"KWCU"_ts, u"Keyword - Cuirass"},
        {"KWDM"_ts, u"Keyword - DummyObject"},
        {"KWDO"_ts, u"Keyword - ClearableLocation"},
        {"KWGE"_ts, u"Keyword - UseGeometryEmitter"},
        {"KWMS"_ts, u"Keyword - MustStop"},
        {"KWOT"_ts, u"Keyword - Skip Outfit Items"},
        {"KWSP"_ts, u"Skyrim - Worldspace"},
        {"KWUA"_ts, u"Keyword - UpdateDuringArchery"},
        {"LHEQ"_ts, u"LeftHand Equip"},
        {"LKHO"_ts, u"Keyword - Hold Location"},
        {"LKPK"_ts, u"Lockpick"},
        {"LMHP"_ts, u"Local Map Hide Plane"},
        {"LRRD"_ts, u"LocRefType - Resource Destructible"},
        {"LRSO"_ts, u"LocRefType - Civil War Soldier"},
        {"LRTB"_ts, u"LocRefType Boss"},
        {"LSIS"_ts, u"Imagespace: Load screen"},
        {"LUMS"_ts, u"Level Up Music"},
        {"MDSC"_ts, u"Music Sound Category"},
        {"MFSN"_ts, u"Magic Fail Sound"},
        {"MGGF"_ts, u"Mages' Guild Faction"},
        {"MHFL"_ts, u"Help - Mods"},
        {"MMCL"_ts, u"Main Menu Cell"},
        {"MMSD"_ts, u"Map Menu Looping Sound"},
        {"MNT2"_ts, u"Keyword - Mount"},
        {"MNTK"_ts, u"Keyword - Mount"},
        {"MORP"_ts, u""},
        {"MTSC"_ts, u"Master Sound Category"},
        {"MVBL"_ts, u"Keyword - Movable"},
        {"MYSF"_ts, u""},
        {"MYSN"_ts, u""},
        {"NASD"_ts, u"No-Activation Sound"},
        {"NDSC"_ts, u"Non-Dialogue Voice Category"},
        {"NMRD"_ts, u"Road Marker"},
        {"NPCK"_ts, u"Keyword - NPC"},
        {"NRNT"_ts, u"Keyword - Nirnroot"},
        {"P3OM"_ts, u"Player's Output Model (3rd Person)"},
        {"PCMD"_ts, u"Player Can Mount Dragon Here List"},
        {"PDLC"_ts, u"Pause During Loading Menu Category"},
        {"PDMC"_ts, u"Pause During Menu Category (Fade)"},
        {"PDSA"_ts, u"Putdown Sound Armor"},
        {"PDSB"_ts, u"Putdown Sound Book"},
        {"PDSG"_ts, u"Putdown Sound Generic"},
        {"PDSI"_ts, u"Putdown Sound Ingredient"},
        {"PDSW"_ts, u"Putdown Sound Weapon"},
        {"PFAC"_ts, u"Player Faction"},
        {"PIMC"_ts, u"Pause During Menu Category (Immediate)"},
        {"PIVV"_ts, u"Player Is Vampire Variable"},
        {"PIWV"_ts, u"Player Is Werewolf Variable"},
        {"PLOC"_ts, u"PersistAll Location"},
        {"PLST"_ts, u"Default Pack List"},
        {"POEQ"_ts, u"Potion Equip"},
        {"POPM"_ts, u"Player's Output Model (1st Person)"},
        {"PPAR"_ts, u""},
        {"PTEM"_ts, u"Package template"},
        {"PTFR"_ts, u"PotentialFollower Faction"},
        {"PTNP"_ts, u"Pathing Test NPC"},
        {"PUSA"_ts, u"Pickup Sound Armor"},
        {"PUSB"_ts, u"Pickup Sound Book"},
        {"PUSG"_ts, u"Pickup Sound Generic"},
        {"PUSI"_ts, u"Pickup Sound Ingredient"},
        {"PUSW"_ts, u"Pickup Sound Weapon"},
        {"PVFA"_ts, u"Player Voice (Female)"},
        {"PVFC"_ts, u"Player Voice (Female Child)"},
        {"PVMA"_ts, u"Player Voice (Male)"},
        {"PVMC"_ts, u"Player Voice (Male Child)"},
        {"PWFD"_ts, u"Wait-For-Dialogue Package"},
        {"RADA"_ts, u""},
        {"RHEQ"_ts, u"RightHand Equip"},
        {"RIVR"_ts, u"Vampire Race"},
        {"RIVS"_ts, u"Vampire Spells"},
        {"RIWR"_ts, u"Werewolf Race"},
        {"RUSG"_ts, u"Keyword - Reusable SoulGem"},
        {"RVBT"_ts, u"Reverb Type"},
        {"SALT"_ts, u"Sitting Angle Limit"},
        {"SAT1"_ts, u"Keyword: Scale Actor To 1.0"},
        {"SCMS"_ts, u"Success Music"},
        {"SCSD"_ts, u"Soul Captured Sound"},
        {"SFDC"_ts, u"SFX To Fade In Dialogue Category"},
        {"SFSN"_ts, u"Shout Fail Sound"},
        {"SKAB"_ts, u"Survival - Keyword Armor Body"},
        {"SKAF"_ts, u"Survival - Keyword Armor Feet"},
        {"SKAH"_ts, u"Survival - Keyword Armor Hands"},
        {"SKAO"_ts, u"Survival - Keyword Armor Head"},
        {"SKCB"_ts, u"Survival - Keyword Clothing Body"},
        {"SKCD"_ts, u"Survival - Keyword Cold"},
        {"SKCF"_ts, u"Survival - Keyword Clothing Feet"},
        {"SKCH"_ts, u"Survival - Keyword Clothing Hands"},
        {"SKCO"_ts, u"Survival - Keyword Clothing Head"},
        {"SKLK"_ts, u"SkeletonKey"},
        {"SKWM"_ts, u"Survival - Keyword Warm"},
        {"SLDM"_ts, u"Snow LOD Material"},
        {"SLHD"_ts, u"Snow LOD Material (HD)"},
        {"SMLT"_ts, u"Keyword: Smelter"},
        {"SMSC"_ts, u"Stats Mute Category"},
        {"SPFK"_ts, u"Keyword - Special Furniture"},
        {"SRCP"_ts, u"Survival - Cold Penalty"},
        {"SRHP"_ts, u"Survival - Hunger Penalty"},
        {"SRSP"_ts, u"Survival - Sleep Penalty"},
        {"SRTP"_ts, u"Survival - Temperature"},
        {"SRVE"_ts, u"Survival Mode Enabled"},
        {"SRVS"_ts, u"Survival Mode - Show Option"},
        {"SRVT"_ts, u"Survival Mode - Toggle"},
        {"SSSC"_ts, u"Stats Music"},
        {"TANN"_ts, u"Keyword: Tanning Rack"},
        {"TKAM"_ts, u"Keyword - Type Ammo"},
        {"TKAR"_ts, u"Keyword - Type Armor"},
        {"TKBK"_ts, u"Keyword - Type Book"},
        {"TKGS"_ts, u"Telekinesis Grab Sound"},
        {"TKIG"_ts, u"Keyword - Type Ingredient"},
        {"TKKY"_ts, u"Keyword - Type Key"},
        {"TKMS"_ts, u"Keyword - Type Misc"},
        {"TKPT"_ts, u"Keyword - Type Potion"},
        {"TKSG"_ts, u"Keyword - Type SoulGem"},
        {"TKTS"_ts, u"Telekinesis Throw Sound"},
        {"TKWP"_ts, u"Keyword - Type Weapon"},
        {"TSSC"_ts, u"Time Sensitive Sound Category"},
        {"TVGF"_ts, u"Thieves' Guild Faction"},
        {"UNDK"_ts, u"Keyword - Undead"},
        {"URVT"_ts, u"Underwater Reverb Type"},
        {"UWLS"_ts, u"Underwater Loop Sound"},
        {"VAMP"_ts, u"Keyword: Vampire"},
        {"VFNC"_ts, u"Vampire Feed No Crime Faction"},
        {"VLOC"_ts, u"Virtual Location"},
        {"VOEQ"_ts, u"Voice Equip"},
        {"WASN"_ts, u"Ward Absorb Sound"},
        {"WBSN"_ts, u"Ward Break Sound"},
        {"WDSN"_ts, u"Ward Deflect Sound"},
        {"WEML"_ts, u"Weapon Material List"},
        {"WMDA"_ts, u"Keyword - Weapon Material Daedric"},
        {"WMDH"_ts, u"Keyword - Weapon Material DraugrHoned"},
        {"WMDR"_ts, u"Keyword - Weapon Material Draugr"},
        {"WMDW"_ts, u"Keyword - Weapon Material Dwarven"},
        {"WMEB"_ts, u"Keyword - Weapon Material Ebony"},
        {"WMEL"_ts, u"Keyword - Weapon Material Elven"},
        {"WMFA"_ts, u"Keyword - Weapon Material Falmer"},
        {"WMFH"_ts, u"Keyword - Weapon Material FalmerHoned"},
        {"WMGL"_ts, u"Keyword - Weapon Material Glass"},
        {"WMIM"_ts, u"Keyword - Weapon Material Imperial"},
        {"WMIR"_ts, u"Keyword - Weapon Material Iron"},
        {"WMOR"_ts, u"Keyword - Weapon Material Orcish"},
        {"WMST"_ts, u"Keyword - Weapon Material Steel"},
        {"WMWE"_ts, u"World Map Weather"},
        {"WMWO"_ts, u"Keyword - Weapon Material Wood"},
        {"WPNC"_ts, u"Keyword - Weapon Material Nordic"},
        {"WPSM"_ts, u"Keyword - Weapon Material Stalhrim"},
        {"WTBA"_ts, u"Keyword - WeaponTypeBoundArrow"},
        {"WWSP"_ts, u"Werewolf Spell"},
    });

template <typename K, typename V, std::size_t N>
inline constexpr V find(const std::array<std::pair<K, V>, N>& table, const K& key)
{
  struct GetKey
  {
    constexpr K operator()(const std::pair<K, V>& element) noexcept
    {
      return element.first;
    }
  };

  const auto it = std::ranges::lower_bound(table, key, std::ranges::less{}, GetKey{});

  if (it != std::ranges::end(table) && it->first == key) {
    return it->second;
  } else {
    return V{};
  }
}

inline constexpr QStringView getFormName(TESFile::Type type)
{
  return find(FormNames, type);
}

inline constexpr QStringView getDefaultObjectName(TESFile::Type type)
{
  return find(DefaultObjectNames, type);
}

}  // namespace TESData

#endif  // TESDATA_FORMNAMES_H
